# Transformer계열 모델에서 사용할 total data

In [119]:
import pandas as pd
import os
import random
import numpy as np
from tqdm import tqdm

import lightgbm as lgb
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score

## 1. 데이터 로딩

In [89]:
data_dir = '../data/' # 경로는 상황에 맞춰서 수정해주세요!

# LOAD TRAINDATA
csv_file_path = os.path.join(data_dir, 'train_data.csv') # 데이터는 대회홈페이지에서 받아주세요 :)
train_data = pd.read_csv(csv_file_path)

# LOAD TESTDATA
test_csv_file_path = os.path.join(data_dir, 'test_data.csv')
test_data = pd.read_csv(test_csv_file_path)
test_data['answerCode'] = test_data['answerCode'].replace(-1, np.nan)

# # LEAVE LAST INTERACTION ONLY
# train_df = test_df[test_df['userID'] == test_df['userID'].shift(-1)]
# test_df = test_df[test_df['userID'] != test_df['userID'].shift(-1)]

# df = pd.concat([df, train_df], ignore_index=True)

## 2. Feature Engineering

In [90]:
train_data['train'] = 1
test_data['train'] = 0
total = pd.concat((train_data, test_data), axis=0)
total = total.sort_values('userID')
total.to_csv(data_dir + 'total_data.csv', index=False)

In [91]:
def feature_engineering(data_dir):
    total = pd.read_csv(os.path.join(data_dir, 'total_data.csv'), parse_dates=["Timestamp"])
    
    ## 유저별 시퀀스를 고려하기 위해 아래와 같이 정렬
    print('Timestamp')
    total['Timestamp'] = pd.to_datetime(total['Timestamp'])
    total.sort_values(by=['userID','Timestamp'], inplace=True)#.reset_index(drop=True)
    
    ############################## 1. Timestamp ##############################
    # 1-1. hour, month
    print('hour', 'month', 'dayofweek')
    total['hour'] = total['Timestamp'].dt.hour
    total['month'] = total['Timestamp'].dt.month
    total['dayofweek'] = total['Timestamp'].dt.dayofweek
    
    # 1-2. 기존 elapsed
    print('elapsed')    # 직전 문제 풀이 소요 시간
    diff = total.loc[:, ['userID', 'Timestamp']].groupby('userID').diff().fillna(pd.Timedelta(seconds=0))
    diff = diff.fillna(pd.Timedelta(seconds=0))
    diff = diff['Timestamp'].apply(lambda x: x.total_seconds())
    total['elapsed'] = diff
    total['elapsed'] = total['elapsed'].apply(lambda x: x if x < 600 and x>=0 else 0)

#     print('current elapsed')    # 현재 문제 풀이 소요 시간
#     diff = total.loc[:, ['userID', 'Timestamp']].groupby('userID').diff().shift(-1).fillna(method='ffill') # 마지막 문제 소요시간을 직전 문제 시간으로 채움
#     diff = diff['Timestamp'].apply(lambda x: x.total_seconds())
#     total['current_elapsed'] = diff
#     total['current_elapsed'] = total['current_elapsed'].apply(lambda x: x if x < 600 and x>=0 else np.nan)
#     total['current_elapsed'] = total['current_elapsed'].fillna(method='ffill')

    print('time class')
    total['timeClass'] = total['elapsed']//5 + 1
    
    print('day_diff')
    day_diff = total.loc[:,['userID','Timestamp']].groupby('userID').diff().fillna(pd.Timedelta(seconds=0))
    day_diff = day_diff['Timestamp'].apply(lambda x: x.days)
    total['day_diff'] = day_diff
    total['day_diff'] = total['day_diff'].apply(lambda x: x if x < 1 and x>=0 else 1)   # 1일 이상 간격 1일로 클립
 
    # 1-3. solved_time
    # 같은 문제 몇번째 푸는지
    print('same_item_cnt')
    total['same_item_cnt'] = total.groupby(['userID', 'assessmentItemID']).cumcount() + 1
   
    # 유저, test, same_item_cnt 구분했을 때 **이전** 문제 푸는데 걸린 시간 > shift, fillna
    print('solved_time_prior')
    diff_shift = total.loc[:, ['userID', 'testId', 'Timestamp', 'same_item_cnt']].groupby(['userID', 'testId', 'same_item_cnt']).diff()#.shift(-1)
    diff_shift = diff_shift['Timestamp'].apply(lambda x: x.total_seconds())
    total['solved_time_prior'] = diff_shift
    total['solved_time_prior'].fillna(0, inplace=True)
    total['solved_time_prior'] = total['solved_time_prior'].apply(lambda x: x if x < 600 and x>=0 else 0)
    # total['solved_time_prior'] = total.groupby(['userID', 'testId', 'same_item_cnt'])['solved_time_prior'].apply(lambda x:x.fillna(x.mean()))
    
    # 유저, test, same_item_cnt 구분했을 때 **이전** 문제 푸는데 걸린 시간 > shift, fillna
    print('solved_time')
    diff_shift = total.loc[:, ['userID', 'testId', 'Timestamp', 'same_item_cnt']].groupby(['userID', 'testId', 'same_item_cnt']).diff().shift(-1)
    diff_shift = diff_shift['Timestamp'].apply(lambda x: x.total_seconds())
    total['solved_time'] = diff_shift
    total['solved_time'] = total['solved_time'].apply(lambda x: x if x < 600 and x>=0 else 0)
    total['solved_time'] = total.groupby(['userID', 'testId', 'same_item_cnt'])['solved_time'].apply(lambda x:x.fillna(x.mean()))
    
    
    ############################## 2. agg값 ##############################
    print('bigcat, smallcat')
    total['bigcat'] = total['testId'].str[2]
    total['smallcat'] = total['testId'].str[7:10]
    
    # # Bigcat_class
    # print('Bigcat_class')
    # total['Bigcat_class'] = round(total['Bigcat_avg']*10)
    
    # # 맞은 사람의 문제별 평균 풀이시간
    # total = total.set_index('assessmentItemID')
    # total['Item_mean_solved_time'] = total[total['answerCode'] == 1].groupby('assessmentItemID')['solved_time_shift'].mean()
    # total = total.reset_index(drop = False)

    ## 2-1. 유저/문제/시험지/카테고리/태그별 평균 정답률
    print('avg')
    total['user_avg'] = total.groupby('userID')['answerCode'].transform('mean')
    total['item_avg'] = total.groupby('assessmentItemID')['answerCode'].transform('mean')
    total['test_avg'] = total.groupby('testId')['answerCode'].transform('mean')
    total['bigcat_avg'] = total.groupby('bigcat')['answerCode'].transform('mean')
    total['tag_avg'] = total.groupby('KnowledgeTag')['answerCode'].transform('mean')

    ## 2-2. 유저/문제/시험지/카테고리/태그별 평균 풀이시간
    print('time_avg')
    total['user_time_avg'] = total.groupby('userID')['solved_time'].transform('mean')
    total['item_time_avg'] = total.groupby('assessmentItemID')['solved_time'].transform('mean')
    total['test_time_avg'] = total.groupby('testId')['solved_time'].transform('mean')
    total['bigcat_time_avg'] = total.groupby('bigcat')['solved_time'].transform('mean')
    total['tag_time_avg'] = total.groupby('KnowledgeTag')['solved_time'].transform('mean')
     
    ## 2-3. 유저/문제/시험지/카테고리/태그별 정답률 표준편차
    print('std')
    total['user_std'] = total.groupby('userID')['answerCode'].transform('std')
    total['item_std'] = total.groupby('assessmentItemID')['answerCode'].transform('std')
    total['test_std'] = total.groupby('testId')['answerCode'].transform('std')
    total['bigcat_std'] = total.groupby('bigcat')['answerCode'].transform('std')
    total['tag_std'] = total.groupby('KnowledgeTag')['answerCode'].transform('std')
    
    ## 2-5. 유저/문제/시험지/카테고리/태그별 누적 개수
    print('cum_cnt')
    total['user_cum_cnt'] = total.groupby('userID')['answerCode'].cumcount() + 1
    total['item_cum_cnt'] = total.groupby('assessmentItemID')['answerCode'].cumcount() + 1
    total['test_cum_cnt'] = total.groupby('testId')['answerCode'].cumcount() + 1
    total['bigcat_cum_cnt'] = total.groupby('bigcat')['answerCode'].cumcount() + 1
    total['tag_cum_cnt'] = total.groupby('KnowledgeTag')['answerCode'].cumcount() + 1
    
    ## 2-6. 유저/문제/시험지/카테고리/태그별 누적정답률
    print('cum_acc')
    total['user_cor_cum_cnt'] = total.groupby('userID')['answerCode'].cumsum()
    total['item_cor_cum_cnt'] = total.groupby('assessmentItemID')['answerCode'].cumsum()
    total['test_cor_cum_cnt'] = total.groupby('testId')['answerCode'].cumsum()
    total['bigcat_cor_cum_cnt'] = total.groupby('bigcat')['answerCode'].cumsum()
    total['tag_cor_cum_cnt'] = total.groupby('KnowledgeTag')['answerCode'].cumsum()
    
    total['user_cum_acc'] = total['user_cor_cum_cnt']/total['user_cum_cnt']
    total['item_cum_acc'] = total['item_cor_cum_cnt']/total['item_cum_cnt']
    total['test_cum_acc'] = total['test_cor_cum_cnt']/total['test_cum_cnt']
    total['bigcat_cum_acc'] = total['bigcat_cor_cum_cnt']/total['bigcat_cum_cnt']
    total['tag_cum_acc'] = total['tag_cor_cum_cnt']/total['tag_cum_cnt']
    
    ## 2-7. 유저의 시험지/카테고리/태그별 누적 정답률
    print('cum_acc per user')
    total['test_cum_cnt_per_user'] = total.groupby(['userID', 'testId'])['answerCode'].cumcount() + 1
    total['bigcat_cum_cnt_per_user'] = total.groupby(['userID', 'bigcat'])['answerCode'].cumcount() + 1
    total['tag_cum_cnt_per_user'] = total.groupby(['userID', 'KnowledgeTag'])['answerCode'].cumcount() + 1
    
    total['test_cor_cum_per_user'] = total.groupby(['userID', 'testId'])['answerCode'].cumsum()
    total['bigcat_cor_cum_per_user'] = total.groupby(['userID', 'bigcat'])['answerCode'].cumsum()
    total['tag_cor_cum_per_user'] = total.groupby(['userID', 'KnowledgeTag'])['answerCode'].cumsum()
    
    total['test_cum_acc_per_user'] = total['test_cor_cum_per_user']/total['test_cum_cnt_per_user']
    total['bigcat_cum_acc_per_user'] = total['bigcat_cor_cum_per_user']/total['bigcat_cum_cnt_per_user']
    total['tag_cum_acc_per_user'] = total['tag_cor_cum_per_user']/total['tag_cum_cnt_per_user']
    
    
    ############################## 3. current ##############################
    ## 3-1. 유저의 해당 문제지 평균 정답률/풀이시간
    print('current')
    total['user_cur_avg'] = total.groupby(['userID', 'testId', 'same_item_cnt'])['answerCode'].transform('mean')
    total['user_cur_time_avg'] = total.groupby(['userID', 'testId', 'same_item_cnt'])['solved_time'].transform('mean')
    
    print('user_rolling')
    total['user_rec_avg_rolling5'] = total.groupby('userID')['answerCode'].transform(lambda x:x.rolling(5, min_periods=1).mean())
    total['user_rec_time_avg_rolling5'] = total.groupby('userID')['solved_time'].transform(lambda x:x.rolling(5, min_periods=1).mean())

    total['user_rec_avg_rolling7'] = total.groupby('userID')['answerCode'].transform(lambda x:x.rolling(7, min_periods=1).mean())
    total['user_rec_time_avg_rolling7'] = total.groupby('userID')['solved_time'].transform(lambda x:x.rolling(7, min_periods=1).mean())
    
    total['user_rec_avg_rolling10'] = total.groupby('userID')['answerCode'].transform(lambda x:x.rolling(10, min_periods=1).mean())
    total['user_rec_time_avg_rolling10'] = total.groupby('userID')['solved_time'].transform(lambda x:x.rolling(10, min_periods=1).mean())
    
    print('item_rolling')
    total['item_rec_avg_rolling5'] = total.groupby('assessmentItemID')['answerCode'].transform(lambda x:x.rolling(5, min_periods=1).mean())
    total['item_rec_time_avg_rolling5'] = total.groupby('assessmentItemID')['solved_time'].transform(lambda x:x.rolling(5, min_periods=1).mean())

    total['item_rec_avg_rolling7'] = total.groupby('assessmentItemID')['answerCode'].transform(lambda x:x.rolling(7, min_periods=1).mean())
    total['item_rec_time_avg_rolling7'] = total.groupby('assessmentItemID')['solved_time'].transform(lambda x:x.rolling(7, min_periods=1).mean())
    
    total['item_rec_avg_rolling10'] = total.groupby('assessmentItemID')['answerCode'].transform(lambda x:x.rolling(10, min_periods=1).mean())
    total['item_rec_time_avg_rolling10'] = total.groupby('assessmentItemID')['solved_time'].transform(lambda x:x.rolling(10, min_periods=1).mean())
    
    
#     # 2-1 유저/문제별 최근 정답횟수 
#     print('retCount_correct_answer')
#     total['user_retCount_correct_answer'] = total.groupby('userID')['answerCode'].transform(lambda x:x.rolling(5, min_periods=1).sum().shift(1))
#     total['item_retCount_correct_answer'] = total.groupby('assessmentItemID')['answerCode'].transform(lambda x:x.rolling(5, min_periods=1).sum().shift(1))
    

#     # 2-1 유저/문제별 최근 정답률
#     print('retCumacc')
#     total['user_retCount'] = total.groupby('userID')['answerCode'].transform(lambda x:x.rolling(5, min_periods=1).count().shift(1))
#     total['user_retCumacc'] = total['user_retCount_correct_answer']/total['user_retCount']

#     total['item_retCount'] = total.groupby('assessmentItemID')['answerCode'].transform(lambda x:x.rolling(5, min_periods=1).count().shift(1))
#     total['item_retCumacc'] = total['item_retCount_correct_answer']/total['item_retCount']
    
    
    ############################## 4. etc ##############################
    ## 문제 번호 추가
    print('item_num')
    total['item_num'] = total['assessmentItemID'].str[7:]
    
    ## 문제 푼 순서 추가 > 상대적 순서?
    print('item_seq')
    total['item_seq'] = total.groupby(['userID', 'testId', 'same_item_cnt']).cumcount()+1
    
    
    # total[['user_correct_answer','item_correct_answer',
    #        'user_Cumacc',
    #        'user_Bigcat_correct_answer', 'user_Bigcat_Cumacc', 
    #        'user_retCount_correct_answer', 'item_retCount_correct_answer',
    #        'user_retCount', 'user_retCumacc',
    #        'item_retCount', 'item_retCumacc']] = total[['user_correct_answer', 'item_correct_answer',
    #                                                     'user_Cumacc',
    #                                                     'user_Bigcat_correct_answer', 'user_Bigcat_Cumacc', 
    #                                                     'user_retCount_correct_answer', 'item_retCount_correct_answer',
    #                                                     'user_retCount', 'user_retCumacc',
    #                                                     'item_retCount', 'item_retCumacc']].fillna(0)
    
    
    
    
    return total

In [92]:
total = feature_engineering(data_dir)
total.head(15)

Timestamp
hour month dayofweek
elapsed
time class
day_diff
same_item_cnt
solved_time_prior
solved_time
bigcat, smallcat
avg
time_avg
std
cum_cnt
cum_acc
cum_acc per user
current
user_rolling
item_rolling
item_num
item_seq

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,train,hour,month,dayofweek,...,user_rec_avg_rolling10,user_rec_time_avg_rolling10,item_rec_avg_rolling5,item_rec_time_avg_rolling5,item_rec_avg_rolling7,item_rec_time_avg_rolling7,item_rec_avg_rolling10,item_rec_time_avg_rolling10,item_num,item_seq
0,0,A060001001,A060000001,1.0,2020-03-24 00:17:11,7224,1,0,3,1,...,1.000000,3.000000,1.0,3.0,1.0,3.0,1.0,3.0,001,1
491,0,A060001002,A060000001,1.0,2020-03-24 00:17:14,7225,1,0,3,1,...,1.000000,5.500000,1.0,8.0,1.0,8.0,1.0,8.0,002,2
492,0,A060001003,A060000001,1.0,2020-03-24 00:17:22,7225,1,0,3,1,...,1.000000,6.000000,1.0,7.0,1.0,7.0,1.0,7.0,003,3
493,0,A060001004,A060000001,1.0,2020-03-24 00:17:29,7225,1,0,3,1,...,1.000000,6.250000,1.0,7.0,1.0,7.0,1.0,7.0,004,4
494,0,A060001005,A060000001,1.0,2020-03-24 00:17:36,7225,1,0,3,1,...,1.000000,7.200000,1.0,11.0,1.0,11.0,1.0,11.0,005,5
495,0,A060001007,A060000001,1.0,2020-03-24 00:17:47,7225,1,0,3,1,...,1.000000,6.000000,1.0,0.0,1.0,0.0,1.0,0.0,007,6
496,0,A060003001,A060000003,0.0,2020-03-26 05:52:03,7226,1,5,3,3,...,0.857143,6.142857,0.0,7.0,0.0,7.0,0.0,7.0,001,1
497,0,A060003002,A060000003,1.0,2020-03-26 05:52:10,7226,1,5,3,3,...,0.875000,13.375000,1.0,64.0,1.0,64.0,1.0,64.0,002,2
498,0,A060003003,A060000003,1.0,2020-03-26 05:53:14,7226,1,5,3,3,...,0.888889,13.555556,1.0,15.0,1.0,15.0,1.0,15.0,003,3
500,0,A060003004,A060000003,1.0,2020-03-26 05:53:29,7226,1,5,3,3,...,0.900000,14.100000,1.0,19.0,1.0,19.0,1.0,19.0,004,4
510,0,A060003005,A060000003,1.0,2020-03-26 05:53:48,7226,1,5,3,3,...,0.900000,14.500000,1.0,7.0,1.0,7.0,1.0,7.0,005,5
501,0,A060003006,A060000003,1.0,2020-03-26 05:53:55,7226,1,5,3,3,...,0.900000,15.300000,1.0,16.0,1.0,16.0,1.0,16.0,006,6
502,0,A060003007,A060000003,1.0,2020-03-26 05:54:11,7226,1,5,3,3,...,0.900000,14.600000,1.0,0.0,1.0,0.0,1.0,0.0,007,7
503,0,A060005001,A060000005,1.0,2020-03-31 05:02:52,7227,1,5,3,1,...,0.900000,15.100000,1.0,12.0,1.0,12.0,1.0,12.0,001,1
504,0,A060005002,A060000005,1.0,2020-03-31 05:03:04,7228,1,5,3,1,...,0.900000,14.700000,1.0,7.0,1.0,7.0,1.0,7.0,002,2

In [93]:
def elo(df, granularity_feature_name):
    def get_new_theta(is_good_answer, beta, left_asymptote, theta, nb_previous_answers):
        return theta + learning_rate_theta(nb_previous_answers) * (
            is_good_answer - probability_of_good_answer(theta, beta, left_asymptote)
        )

    def get_new_beta(is_good_answer, beta, left_asymptote, theta, nb_previous_answers):
        return beta - learning_rate_beta(nb_previous_answers) * (
            is_good_answer - probability_of_good_answer(theta, beta, left_asymptote)
        )

    def learning_rate_theta(nb_answers):
        return max(0.3 / (1 + 0.01 * nb_answers), 0.04)

    def learning_rate_beta(nb_answers):
        return 1 / (1 + 0.05 * nb_answers)

    def probability_of_good_answer(theta, beta, left_asymptote):
        return left_asymptote + (1 - left_asymptote) * sigmoid(theta - beta)

    def sigmoid(x):
        return 1 / (1 + np.exp(-x))

    def estimate_parameters(answers_df, granularity_feature_name):
        item_parameters = {
            granularity_feature_value: {"beta": 0, "nb_answers": 0}
            for granularity_feature_value in np.unique(
                answers_df[granularity_feature_name]
            )
        }
        student_parameters = {
            student_id: {"theta": 0, "nb_answers": 0}
            for student_id in np.unique(answers_df.userID)
        }

        print("Parameter estimation is starting...", flush=True)

        for student_id, item_id, left_asymptote, answered_correctly in tqdm(
            zip(
                answers_df.userID.values,
                answers_df[granularity_feature_name].values,
                answers_df.left_asymptote.values,
                answers_df.answerCode.values,
            ),
            total=len(answers_df),
        ):
            theta = student_parameters[student_id]["theta"]
            beta = item_parameters[item_id]["beta"]

            item_parameters[item_id]["beta"] = get_new_beta(
                answered_correctly,
                beta,
                left_asymptote,
                theta,
                item_parameters[item_id]["nb_answers"],
            )
            student_parameters[student_id]["theta"] = get_new_theta(
                answered_correctly,
                beta,
                left_asymptote,
                theta,
                student_parameters[student_id]["nb_answers"],
            )

            item_parameters[item_id]["nb_answers"] += 1
            student_parameters[student_id]["nb_answers"] += 1

        print(f"Theta & beta estimations on {granularity_feature_name} are completed.")
        return student_parameters, item_parameters

    def gou_func(theta, beta):
        return 1 / (1 + np.exp(-(theta - beta)))

    df["left_asymptote"] = 0

    print(f"Dataset of shape {df.shape}")
    print(f"Columns are {list(df.columns)}")

    student_parameters, item_parameters = estimate_parameters(df, granularity_feature_name)
    return student_parameters, item_parameters
#     print(item_parameters)

#     prob = [
#         gou_func(student_parameters[student]["theta"], item_parameters[item]["beta"])
#         for student, item in zip(df.userID.values, df[granularity_feature_name].values)
#     ]

#     df["elo_"+granularity_feature_name] = prob

#     return df

In [94]:
def gou_func(theta, beta):
    return 1 / (1 + np.exp(-(theta - beta)))

## elo
print('elo')
total_notnull = total[total['answerCode'].isna()==False]
cols = ["assessmentItemID", "testId", "KnowledgeTag"]
for col in cols:
    student_parameters, item_parameters = elo(total_notnull, col)
    
    prob = [
        gou_func(student_parameters[student]["theta"], item_parameters[item]["beta"])
        for student, item in zip(total.userID.values, total[col].values)
    ]

    total["elo_"+col] = prob

elo

/tmp/ipykernel_80561/4040132262.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["left_asymptote"] = 0

Dataset of shape (2525956, 74)
Columns are ['userID', 'assessmentItemID', 'testId', 'answerCode', 'Timestamp', 'KnowledgeTag', 'train', 'hour', 'month', 'dayofweek', 'elapsed', 'timeClass', 'day_diff', 'same_item_cnt', 'solved_time_prior', 'solved_time', 'bigcat', 'smallcat', 'user_avg', 'item_avg', 'test_avg', 'bigcat_avg', 'tag_avg', 'user_time_avg', 'item_time_avg', 'test_time_avg', 'bigcat_time_avg', 'tag_time_avg', 'user_std', 'item_std', 'test_std', 'bigcat_std', 'tag_std', 'user_cum_cnt', 'item_cum_cnt', 'test_cum_cnt', 'bigcat_cum_cnt', 'tag_cum_cnt', 'user_cor_cum_cnt', 'item_cor_cum_cnt', 'test_cor_cum_cnt', 'bigcat_cor_cum_cnt', 'tag_cor_cum_cnt', 'user_cum_acc', 'item_cum_acc', 'test_cum_acc', 'bigcat_cum_acc', 'tag_cum_acc', 'test_cum_cnt_per_user', 'bigcat_cum_cnt_per_user', 'tag_cum_cnt_per_user', 'test_cor_cum_per_user', 'bigcat_cor_cum_per_user', 'tag_cor_cum_per_user', 'test_cum_acc_per_user', 'bigcat_cum_acc_per_user', 'tag_cum_acc_per_user', 'user_cur_avg', 'user_cur_time_avg', 'user_rec_avg_rolling5', 'user_rec_time_avg_rolling5', 'user_rec_avg_rolling7', 'user_rec_time_avg_rolling7', 'user_rec_avg_rolling10', 'user_rec_time_avg_rolling10', 'item_rec_avg_rolling5', 'item_rec_time_avg_rolling5', 'item_rec_avg_rolling7', 'item_rec_time_avg_rolling7', 'item_rec_avg_rolling10', 'item_rec_time_avg_rolling10', 'item_num', 'item_seq', 'left_asymptote']
Parameter estimation is starting...

100%|██████████| 2525956/2525956 [00:20<00:00, 122476.54it/s]

Theta & beta estimations on assessmentItemID are completed.

/tmp/ipykernel_80561/4040132262.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["left_asymptote"] = 0

Dataset of shape (2525956, 74)
Columns are ['userID', 'assessmentItemID', 'testId', 'answerCode', 'Timestamp', 'KnowledgeTag', 'train', 'hour', 'month', 'dayofweek', 'elapsed', 'timeClass', 'day_diff', 'same_item_cnt', 'solved_time_prior', 'solved_time', 'bigcat', 'smallcat', 'user_avg', 'item_avg', 'test_avg', 'bigcat_avg', 'tag_avg', 'user_time_avg', 'item_time_avg', 'test_time_avg', 'bigcat_time_avg', 'tag_time_avg', 'user_std', 'item_std', 'test_std', 'bigcat_std', 'tag_std', 'user_cum_cnt', 'item_cum_cnt', 'test_cum_cnt', 'bigcat_cum_cnt', 'tag_cum_cnt', 'user_cor_cum_cnt', 'item_cor_cum_cnt', 'test_cor_cum_cnt', 'bigcat_cor_cum_cnt', 'tag_cor_cum_cnt', 'user_cum_acc', 'item_cum_acc', 'test_cum_acc', 'bigcat_cum_acc', 'tag_cum_acc', 'test_cum_cnt_per_user', 'bigcat_cum_cnt_per_user', 'tag_cum_cnt_per_user', 'test_cor_cum_per_user', 'bigcat_cor_cum_per_user', 'tag_cor_cum_per_user', 'test_cum_acc_per_user', 'bigcat_cum_acc_per_user', 'tag_cum_acc_per_user', 'user_cur_avg', 'user_cur_time_avg', 'user_rec_avg_rolling5', 'user_rec_time_avg_rolling5', 'user_rec_avg_rolling7', 'user_rec_time_avg_rolling7', 'user_rec_avg_rolling10', 'user_rec_time_avg_rolling10', 'item_rec_avg_rolling5', 'item_rec_time_avg_rolling5', 'item_rec_avg_rolling7', 'item_rec_time_avg_rolling7', 'item_rec_avg_rolling10', 'item_rec_time_avg_rolling10', 'item_num', 'item_seq', 'left_asymptote']
Parameter estimation is starting...

100%|██████████| 2525956/2525956 [00:20<00:00, 122220.96it/s]

Theta & beta estimations on testId are completed.
Dataset of shape (2525956, 74)
Columns are ['userID', 'assessmentItemID', 'testId', 'answerCode', 'Timestamp', 'KnowledgeTag', 'train', 'hour', 'month', 'dayofweek', 'elapsed', 'timeClass', 'day_diff', 'same_item_cnt', 'solved_time_prior', 'solved_time', 'bigcat', 'smallcat', 'user_avg', 'item_avg', 'test_avg', 'bigcat_avg', 'tag_avg', 'user_time_avg', 'item_time_avg', 'test_time_avg', 'bigcat_time_avg', 'tag_time_avg', 'user_std', 'item_std', 'test_std', 'bigcat_std', 'tag_std', 'user_cum_cnt', 'item_cum_cnt', 'test_cum_cnt', 'bigcat_cum_cnt', 'tag_cum_cnt', 'user_cor_cum_cnt', 'item_cor_cum_cnt', 'test_cor_cum_cnt', 'bigcat_cor_cum_cnt', 'tag_cor_cum_cnt', 'user_cum_acc', 'item_cum_acc', 'test_cum_acc', 'bigcat_cum_acc', 'tag_cum_acc', 'test_cum_cnt_per_user', 'bigcat_cum_cnt_per_user', 'tag_cum_cnt_per_user', 'test_cor_cum_per_user', 'bigcat_cor_cum_per_user', 'tag_cor_cum_per_user', 'test_cum_acc_per_user', 'bigcat_cum_acc_per_user', 'tag_cum_acc_per_user', 'user_cur_avg', 'user_cur_time_avg', 'user_rec_avg_rolling5', 'user_rec_time_avg_rolling5', 'user_rec_avg_rolling7', 'user_rec_time_avg_rolling7', 'user_rec_avg_rolling10', 'user_rec_time_avg_rolling10', 'item_rec_avg_rolling5', 'item_rec_time_avg_rolling5', 'item_rec_avg_rolling7', 'item_rec_time_avg_rolling7', 'item_rec_avg_rolling10', 'item_rec_time_avg_rolling10', 'item_num', 'item_seq', 'left_asymptote']
Parameter estimation is starting...

/tmp/ipykernel_80561/4040132262.py:74: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["left_asymptote"] = 0
100%|██████████| 2525956/2525956 [00:20<00:00, 123261.21it/s]

Theta & beta estimations on KnowledgeTag are completed.

In [95]:
total.head()

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,train,hour,month,dayofweek,...,item_rec_time_avg_rolling5,item_rec_avg_rolling7,item_rec_time_avg_rolling7,item_rec_avg_rolling10,item_rec_time_avg_rolling10,item_num,item_seq,elo_assessmentItemID,elo_testId,elo_KnowledgeTag
0,0,A060001001,A060000001,1.0,2020-03-24 00:17:11,7224,1,0,3,1,...,3.0,1.0,3.0,1.0,3.0,001,1,0.980777,0.962586,0.966368
491,0,A060001002,A060000001,1.0,2020-03-24 00:17:14,7225,1,0,3,1,...,8.0,1.0,8.0,1.0,8.0,002,2,0.973329,0.962586,0.932581
492,0,A060001003,A060000001,1.0,2020-03-24 00:17:22,7225,1,0,3,1,...,7.0,1.0,7.0,1.0,7.0,003,3,0.947326,0.962586,0.932581
493,0,A060001004,A060000001,1.0,2020-03-24 00:17:29,7225,1,0,3,1,...,7.0,1.0,7.0,1.0,7.0,004,4,0.974927,0.962586,0.932581
494,0,A060001005,A060000001,1.0,2020-03-24 00:17:36,7225,1,0,3,1,...,11.0,1.0,11.0,1.0,11.0,005,5,0.961414,0.962586,0.932581

In [96]:
fill_columns = ['user_cor_cum_cnt', 'item_cor_cum_cnt', 'test_cor_cum_cnt', 'bigcat_cor_cum_cnt', 'tag_cor_cum_cnt',
               'user_cum_acc', 'item_cum_acc', 'test_cum_acc', 'bigcat_cum_acc', 'tag_cum_acc',
               'test_cor_cum_per_user', 'bigcat_cor_cum_per_user', 'tag_cor_cum_per_user',
               'test_cum_acc_per_user', 'bigcat_cum_acc_per_user', 'tag_cum_acc_per_user',
               'item_rec_avg_rolling5', 'item_rec_avg_rolling7', 'item_rec_avg_rolling10'
               ]

total[fill_columns] = total[fill_columns].fillna(method='ffill')

In [97]:
total.isna().sum().sum()

744

In [98]:
# save total_data
total.to_csv(data_dir + 'total_data_hyein6.csv', index=False)

In [99]:
total = pd.read_csv('../data/total_data_hyein6.csv')

In [100]:
total.columns

Index(['userID', 'assessmentItemID', 'testId', 'answerCode', 'Timestamp',
       'KnowledgeTag', 'train', 'hour', 'month', 'dayofweek', 'elapsed',
       'timeClass', 'day_diff', 'same_item_cnt', 'solved_time_prior',
       'solved_time', 'bigcat', 'smallcat', 'user_avg', 'item_avg', 'test_avg',
       'bigcat_avg', 'tag_avg', 'user_time_avg', 'item_time_avg',
       'test_time_avg', 'bigcat_time_avg', 'tag_time_avg', 'user_std',
       'item_std', 'test_std', 'bigcat_std', 'tag_std', 'user_cum_cnt',
       'item_cum_cnt', 'test_cum_cnt', 'bigcat_cum_cnt', 'tag_cum_cnt',
       'user_cor_cum_cnt', 'item_cor_cum_cnt', 'test_cor_cum_cnt',
       'bigcat_cor_cum_cnt', 'tag_cor_cum_cnt', 'user_cum_acc', 'item_cum_acc',
       'test_cum_acc', 'bigcat_cum_acc', 'tag_cum_acc',
       'test_cum_cnt_per_user', 'bigcat_cum_cnt_per_user',
       'tag_cum_cnt_per_user', 'test_cor_cum_per_user',
       'bigcat_cor_cum_per_user', 'tag_cor_cum_per_user',
       'test_cum_acc_per_user', 'bigcat_cum_acc_per_user',
       'tag_cum_acc_per_user', 'user_cur_avg', 'user_cur_time_avg',
       'user_rec_avg_rolling5', 'user_rec_time_avg_rolling5',
       'user_rec_avg_rolling7', 'user_rec_time_avg_rolling7',
       'user_rec_avg_rolling10', 'user_rec_time_avg_rolling10',
       'item_rec_avg_rolling5', 'item_rec_time_avg_rolling5',
       'item_rec_avg_rolling7', 'item_rec_time_avg_rolling7',
       'item_rec_avg_rolling10', 'item_rec_time_avg_rolling10', 'item_num',
       'item_seq', 'elo_assessmentItemID', 'elo_testId', 'elo_KnowledgeTag'],
      dtype='object')

In [117]:
total[total['answerCode'].isna()][['userID', #'assessmentItemID', 'testId', 'KnowledgeTag',
                                   #'timeClass', 
                                   'day_diff', 'item_num', #'item_seq', 
                                   'bigcat', 'smallcat', 
                                   'elapsed', 'solved_time_prior',
                                   'user_avg', 'item_avg', 'test_avg', 'bigcat_avg', 'tag_avg', 
                                   # 'user_std', 'item_std', 'test_std', 'bigcat_std', 'tag_std', 
                                   # 'user_cum_acc', 'item_cum_acc', 'test_cum_acc', 'bigcat_cum_acc', 'tag_cum_acc', 
                                   # 'test_cum_acc_per_user', 'bigcat_cum_acc_per_user', 'tag_cum_acc_per_user', 
                                   'user_cur_avg', 'user_cur_time_avg',
                                   'user_rec_avg_rolling5', 'item_rec_avg_rolling5', 
                                   'elo_assessmentItemID', 'elo_testId', 'elo_KnowledgeTag', 'answerCode']].head(20)

,userID,day_diff,item_num,bigcat,smallcat,elapsed,solved_time_prior,user_avg,item_avg,test_avg,bigcat_avg,tag_avg,user_cur_avg,user_cur_time_avg,user_rec_avg_rolling5,item_rec_avg_rolling5,elo_assessmentItemID,elo_testId,elo_KnowledgeTag,answerCode
2989,3,0,8,5,133,46.0,46.0,0.692754,0.534137,0.655328,0.659098,0.559557,0.857143,39.500000,0.75,0.00,0.469409,0.612941,0.655560,NaN
3660,4,0,8,7,146,23.0,23.0,0.694030,0.613793,0.651883,0.521761,0.546420,0.857143,21.500000,1.00,1.00,0.568044,0.699515,0.614923,NaN
10860,13,0,8,7,111,8.0,8.0,0.695289,0.369478,0.456728,0.521761,0.494326,0.428571,13.000000,0.25,0.00,0.193095,0.281260,0.345764,NaN
15278,17,0,6,9,64,75.0,75.0,0.818904,0.272727,0.445743,0.454680,0.419317,1.000000,63.333333,1.00,1.00,0.392463,0.614123,0.526969,NaN
23531,26,0,7,6,135,17.0,17.0,0.759067,0.313253,0.640366,0.712279,0.609602,0.666667,39.285714,0.50,0.00,0.351426,0.755810,0.694956,NaN
26895,29,0,5,2,190,30.0,30.0,0.847597,0.712375,0.739827,0.738023,0.710810,1.000000,20.800000,1.00,0.50,0.905946,0.932831,0.908537,NaN
39887,45,0,5,4,136,4.0,4.0,0.688827,0.608696,0.721815,0.680256,0.702731,0.250000,20.000000,0.25,0.25,0.681712,0.729394,0.715109,NaN
47628,53,0,5,4,140,20.0,20.0,0.523121,0.385135,0.713235,0.680256,0.712121,0.500000,8.200000,0.50,0.50,0.086398,0.385757,0.375588,NaN
51927,58,0,7,7,159,2.0,2.0,0.364198,0.389558,0.477978,0.521761,0.366820,0.142857,1.625000,0.00,0.50,0.122516,0.233196,0.148972,NaN
57352,64,0,8,7,146,2.0,2.0,0.833727,0.613793,0.651883,0.521761,0.546420,1.000000,1.500000,1.00,0.75,0.864322,0.897751,0.881565,NaN
65977,76,0,7,5,149,30.0,30.0,0.709046,0.642276,0.700458,0.659098,0.728078,0.333333,28.714286,0.25,0.50,0.668614,0.719968,0.763698,NaN
69128,79,0,8,7,164,208.0,208.0,0.727783,0.204082,0.488722,0.521761,0.543577,0.857143,228.875000,0.75,0.00,0.224368,0.553379,0.781651,NaN
84101,94,0,5,1,146,15.0,15.0,0.841983,0.931507,0.919571,0.801686,0.883094,1.000000,26.800000,1.00,1.00,0.961201,0.940438,0.908557,NaN
107130,120,0,7,5,153,26.0,26.0,0.716698,0.288066,0.551922,0.659098,0.607407,0.833333,39.571429,0.75,0.25,0.493753,0.770600,0.824584,NaN
136768,159,0,7,5,141,107.0,107.0,0.751334,0.608871,0.839817,0.659098,0.746831,0.833333,29.000000,0.75,0.25,0.614219,0.863825,0.751191,NaN
148130,172,0,5,2,133,11.0,11.0,0.819620,0.816054,0.811207,0.738023,0.785029,1.000000,24.000000,1.00,0.75,0.959212,0.955587,0.946142,NaN
163216,193,0,8,7,151,3.0,3.0,0.334586,0.358871,0.466466,0.521761,0.451812,0.285714,33.875000,0.00,0.75,0.176659,0.310396,0.288500,NaN
168083,200,0,5,2,144,31.0,31.0,0.739524,0.831650,0.843019,0.738023,0.824863,1.000000,17.400000,1.00,0.75,0.903127,0.897689,0.876367,NaN
171153,203,0,7,6,73,126.0,126.0,0.843584,0.641129,0.677918,0.712279,0.768461,1.000000,118.857143,1.00,0.50,0.932229,0.908893,0.929181,NaN
172094,204,0,8,7,145,254.0,254.0,0.485106,0.314516,0.550826,0.521761,0.546420,0.142857,36.000000,0.25,0.00,0.148528,0.406552,0.343421,NaN

In [120]:
ex = pd.read_csv('../data/total_data.csv')
ex.head()

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,train,same_item_cnt,prior_elapsed,current_elapsed,...,Bigcat_class,assess_count,tag_count,item_seq,user_retCount_correct_answer,item_retCount_correct_answer,user_retCount,user_retCumacc,item_retCount,item_retCumacc
0,0,A060001001,A060000001,1.0,2020-03-24 00:17:11,7224,1,1,0.0,3.0,...,7.0,0,0,1,0.0,0.0,0.0,0.0,0.0,0.0
1,0,A060001002,A060000001,1.0,2020-03-24 00:17:14,7225,1,1,3.0,8.0,...,7.0,1,1,2,1.0,0.0,1.0,1.0,0.0,0.0
2,0,A060001003,A060000001,1.0,2020-03-24 00:17:22,7225,1,1,8.0,7.0,...,7.0,2,2,3,2.0,0.0,2.0,1.0,0.0,0.0
3,0,A060001004,A060000001,1.0,2020-03-24 00:17:29,7225,1,1,7.0,7.0,...,7.0,3,3,4,3.0,0.0,3.0,1.0,0.0,0.0
4,0,A060001005,A060000001,1.0,2020-03-24 00:17:36,7225,1,1,7.0,11.0,...,7.0,4,4,5,4.0,0.0,4.0,1.0,0.0,0.0

In [121]:
total.head()

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,train,hour,month,dayofweek,...,item_rec_time_avg_rolling5,item_rec_avg_rolling7,item_rec_time_avg_rolling7,item_rec_avg_rolling10,item_rec_time_avg_rolling10,item_num,item_seq,elo_assessmentItemID,elo_testId,elo_KnowledgeTag
0,0,A060001001,A060000001,1.0,2020-03-24 00:17:11,7224,1,0,3,1,...,3.0,1.0,3.0,1.0,3.0,1,1,0.980777,0.962586,0.966368
1,0,A060001002,A060000001,1.0,2020-03-24 00:17:14,7225,1,0,3,1,...,8.0,1.0,8.0,1.0,8.0,2,2,0.973329,0.962586,0.932581
2,0,A060001003,A060000001,1.0,2020-03-24 00:17:22,7225,1,0,3,1,...,7.0,1.0,7.0,1.0,7.0,3,3,0.947326,0.962586,0.932581
3,0,A060001004,A060000001,1.0,2020-03-24 00:17:29,7225,1,0,3,1,...,7.0,1.0,7.0,1.0,7.0,4,4,0.974927,0.962586,0.932581
4,0,A060001005,A060000001,1.0,2020-03-24 00:17:36,7225,1,0,3,1,...,11.0,1.0,11.0,1.0,11.0,5,5,0.961414,0.962586,0.932581